import { TextEdit } from "std-widgets.slint";
import { Callabler } from "../globals/callabler.slint";
import { Translations } from "../globals/translations.slint";
import { PopupBase } from "../components/popup_base.slint";
import { GuiState } from "../globals/gui_state.slint";

export component PopupNewDirectories inherits Rectangle {
    private property <length> popup_width: 350px;
    private property <length> popup_min_height: 200px;
    callback show_popup();

    property <bool> included_paths;
    private property <string> text_data;

    popup_window := PopupBase {
        width: popup_width;
        popup_min_height: popup_min_height;
        x: (parent.width - popup_width) / 2.0;
        y: (parent.height - self.height) / 2.0;
        title_text <=> Translations.popup_new_directories_title_text;
        enabled_ok_button: text_data != "";

        VerticalLayout {
            TextEdit {
                vertical-stretch: 1.0;
                text <=> text_data;
            }
        }

        ok_clicked => {
            Callabler.added_manual_paths(GuiState.choosing_include_directories, text_data);
        }
    }

    show_popup() => {
        text_data = "";
        popup_window.show();
    }
}
