import { PopupBase } from "../components/popup_base.slint";
import { Translations } from "../globals/translations.slint";
import { CheckBox } from "std-widgets.slint";
import { Settings } from "../globals/settings.slint";
import { PopupCenteredText } from "../components/popup_centered_text.slint";

export component PopupCleanExif inherits Rectangle {
    in-out property <string> title_text;

    callback action_confirmed();

    private property <length> popup_width: 420px;
    private property <length> popup_min_height: 200px;
    callback show_popup();

    popup_window := PopupBase {
        width: popup_width;
        popup_min_height: popup_min_height;
        x: (parent.width - popup_width) / 2.0;
        y: (parent.height - self.height) / 2.0;
        title_text <=> root.title_text;

        VerticalLayout {
            spacing: 8px;

            Rectangle { height: 8px; }

            HorizontalLayout {
                spacing: 0px;

                Rectangle { width: 8px; }

                VerticalLayout {
                    spacing: 8px;

                    PopupCenteredText { text: Translations.clean_confirmation_text; }

                    CheckBox { text: Translations.clean_exif_overwrite_files_text; checked <=> Settings.popup_clean_exif_overwrite_files; }

                    Rectangle { height: 10px; }
                }

                Rectangle { width: 8px; }
            }
        }

        ok_clicked => {
            root.action_confirmed();
        }

        cancel_clicked => {
        }
    }

    show_popup() => { popup_window.show(); }
}
