import { PopupBase } from "../components/popup_base.slint";
import { PopupCenteredText } from "../components/popup_centered_text.slint";

export component PopupActionConfirm inherits Rectangle {
    in-out property <string> title_text;
    in-out property <string> confirmation_text;
    callback action_confirmed();

    private property <length> popup_width: 350px;
    private property <length> popup_min_height: 150px;
    callback show_popup();

    popup_window := PopupBase {
        width: popup_width;
        popup_min_height: popup_min_height;
        x: (parent.width - popup_width) / 2.0;
        y: (parent.height - self.height) / 2.0;
        title_text <=> root.title_text;

        VerticalLayout {
            PopupCenteredText {
                text <=> root.confirmation_text;
            }
        }

        ok_clicked => {
            root.action_confirmed();
        }
    }

    show_popup() => {
        popup_window.show();
    }
}
