import { Callabler } from "../globals/callabler.slint";
import { Translations } from "../globals/translations.slint";
import { PopupBase } from "../components/popup_base.slint";
import { PopupCenteredText } from "../components/popup_centered_text.slint";

export component PopupDelete inherits Rectangle {
    private property <length> popup_width: 350px;
    private property <length> popup_min_height: 150px;
    callback show_popup();

    popup_window := PopupBase {
        width: popup_width;
        popup_min_height: popup_min_height;
        x: (parent.width - popup_width) / 2.0;
        y: (parent.height - self.height) / 2.0;
        title_text <=> Translations.delete_text;

        VerticalLayout {
            PopupCenteredText {
                text <=> Translations.delete_confirmation_text;
            }
        }

        ok_clicked => {
            Callabler.delete_selected_items();
        }
    }

    show_popup() => {
        popup_window.show();
    }
}
