import { PopupBase } from "../components/popup_base.slint";
import { Translations } from "../globals/translations.slint";
import { CheckBox, ScrollView } from "std-widgets.slint";
import { Settings } from "../globals/settings.slint";
import { PopupCenteredText } from "../components/popup_centered_text.slint";
import { LabeledComboRow, LabeledSliderRow } from "../components/labeled_rows.slint";

export component PopupCropVideo inherits Rectangle {
    in-out property <string> title_text;

    callback action_confirmed();

    out property <length> popup_width: 440px;
    out property <length> popup_height: 320px;
    callback show_popup();

    popup_window := PopupBase {
        width: popup_width;
        height: popup_height;
        title_text <=> root.title_text;

        VerticalLayout {
            spacing: 8px;

            Rectangle { height: 8px; }

            HorizontalLayout {
                spacing: 0px;

                Rectangle { width: 8px; }

                ScrollView {
                    vertical-stretch: 1.0;

                    VerticalLayout {
                        spacing: 8px;

                        PopupCenteredText { text: Translations.crop_video_confirmation_text; }

                        CheckBox { text: Translations.crop_reencode_video_text; checked <=> Settings.popup_crop_video_reencode; }

                        LabeledComboRow {
                            label_text: Translations.subsettings_video_optimizer_video_codec_text;
                            model <=> Settings.video_optimizer_sub_video_codec_config;
                            current_index <=> Settings.video_optimizer_sub_video_codec_index;
                            current_value <=> Settings.video_optimizer_sub_video_codec_value;
                            enabled: Settings.popup_crop_video_reencode;
                        }

                        LabeledSliderRow {
                            label_text: Translations.subsettings_video_optimizer_video_quality_text;
                            minimum: 0.0;
                            maximum: 51.0;
                            value <=> Settings.popup_crop_video_quality;
                            enabled: Settings.popup_crop_video_reencode;
                            end_text: Math.round(Settings.popup_crop_video_quality) + " / 51";
                        }

                        CheckBox { text: Translations.optimize_overwrite_files_text; checked <=> Settings.popup_crop_video_overwrite_files; }

                        Rectangle { height: 10px; }
                    }
                }

                Rectangle { width: 8px; }
            }
        }

        ok_clicked => {
            root.action_confirmed();
        }

        cancel_clicked => {
        }
    }

    show_popup() => { popup_window.show(); }
}
