import { Callabler } from "../globals/callabler.slint";
import { Translations } from "../globals/translations.slint";
import { PopupBase } from "../components/popup_base.slint";
import { PopupCenteredText } from "../components/popup_centered_text.slint";

export component PopupSave inherits Rectangle {
    private property <length> popup_width: 500px;
    private property <length> popup_min_height: 150px;
    callback show_popup();

    popup_window := PopupBase {
        width: popup_width;
        popup_min_height: popup_min_height;
        x: (parent.width - popup_width) / 2.0;
        y: (parent.height - self.height) / 2.0;
        title_text <=> Translations.popup_save_title_text;

        VerticalLayout {
            PopupCenteredText {
                text: Translations.popup_save_message_text + "\n\n" + Translations.do_you_want_to_continue_text;
            }
        }

        ok_clicked => {
            Callabler.save_results();
        }
    }

    show_popup() => {
        popup_window.show();
    }
}
