pub mod bad_extensions;
pub mod big_file;
pub mod broken_files;
pub mod duplicate;
pub mod empty_files;
pub mod empty_folder;
pub mod invalid_symlinks;
pub mod same_music;
pub mod similar_images;
#[cfg(feature = "similar_videos")]
pub mod similar_videos;
pub mod temporary;
