import { Button, VerticalBox , HorizontalBox, TabWidget, ListView, StandardListView, StandardTableView, CheckBox} from "std-widgets.slint";
import {CurrentTab} from "common.slint";

component TabItem {
    in property <bool> scanning;
    in-out property <CurrentTab> active-tab;
    in property <string> text;
    in property <CurrentTab> curr_tab;

    Button {
        enabled: !scanning;
        text: root.text;
        clicked => { root.active-tab = root.curr-tab; }
    }
}

export component LeftSidePanel {
    in-out property <CurrentTab> active-tab;
    in-out property <bool> scanning;
    width: 120px;

    VerticalLayout {
        spacing: 20px;
        Rectangle {
            height: 100px;
            Image {
                width: root.width;
                source: @image-url("../icons/logo.png");
            }
        }
        VerticalLayout {
            spacing: 3px;
            alignment: center;
            
            TabItem {
                scanning: scanning;
                text: "Empty Folders";
                active-tab <=> root.active-tab;
                curr_tab: CurrentTab.EmptyFolders;
            }
            TabItem {
                scanning: scanning;
                text: "Empty Files";
                active-tab <=> root.active-tab;
                curr_tab: CurrentTab.EmptyFiles;
            }
            TabItem {
                scanning: scanning;
                text: "Similar Images";
                active-tab <=> root.active-tab;
                curr_tab: CurrentTab.SimilarImages;
            }
        }
        HorizontalLayout {
            height: 20px;
            alignment: end;
            Image {
                width: 20px;
                source: @image-url("../icons/settings.png");
            }
        }
    }
}