pub struct TestCase {
    pub name: &'static str,
    /// Args passed to czkawka. Use the literal string `"TestFiles"` as the
    /// directory placeholder – it will be replaced with the actual per-test
    /// unique directory at runtime.
    pub args: &'static [&'static str],
    pub expected_files: &'static [&'static str],
    pub expected_folders: &'static [&'static str],
    pub expected_symlinks: &'static [&'static str],
}

pub fn all_test_cases() -> Vec<TestCase> {
    vec![
        // ── Misc ──────────────────────────────────────────────────────────────
        TestCase {
            name: "empty_files",
            args: &["empty-files", "-d", "TestFiles", "-D", "-W"],
            expected_files: &["EmptyFile"],
            expected_folders: &[],
            expected_symlinks: &[],
        },
        TestCase {
            name: "big_files",
            args: &["big", "-d", "TestFiles", "-n", "2", "-D", "-W"],
            expected_files: &["Music/M4.mp3", "Videos/V3.webm"],
            expected_folders: &[],
            expected_symlinks: &[],
        },
        TestCase {
            name: "smallest_files",
            args: &["big", "-d", "TestFiles", "-J", "-n", "5", "-D", "-W"],
            expected_files: &[
                "Broken/Br.jpg",
                "Broken/Br.mp3",
                "Broken/Br.pdf",
                "Broken/Br.zip",
                "EmptyFolders/ThreeButNot/KEKEKE",
            ],
            expected_folders: &[],
            expected_symlinks: &[],
        },
        TestCase {
            name: "biggest_files",
            args: &["big", "-d", "TestFiles", "-n", "6", "-D", "-W"],
            expected_files: &[
                "Music/M3.flac",
                "Music/M4.mp3",
                "Videos/V1.mp4",
                "Videos/V2.mp4",
                "Videos/V3.webm",
                "Videos/V5.mp4",
            ],
            expected_folders: &[],
            expected_symlinks: &[],
        },
        TestCase {
            name: "empty_folders",
            args: &["empty-folders", "-d", "TestFiles", "-D", "-W"],
            expected_files: &[],
            expected_folders: &["EmptyFolders/One", "EmptyFolders/Two", "EmptyFolders/Two/TwoInside"],
            expected_symlinks: &[],
        },
        TestCase {
            name: "temporary_files",
            args: &["temp", "-d", "TestFiles", "-D", "-W"],
            expected_files: &["Temporary/Boczze.cache"],
            expected_folders: &[],
            expected_symlinks: &[],
        },
        TestCase {
            name: "symlinks_files",
            args: &["symlinks", "-d", "TestFiles", "-D", "-W"],
            expected_files: &[],
            expected_folders: &[],
            expected_symlinks: &["Symlinks/EmptyFiles"],
        },
        // ── Duplicates ────────────────────────────────────────────────────────
        TestCase {
            name: "dup_one_oldest",
            args: &["dup", "-d", "TestFiles", "-D", "OO", "-W"],
            expected_files: &["Images/A2.jpg", "Music/M5.mp3", "Videos/V2.mp4"],
            expected_folders: &[],
            expected_symlinks: &[],
        },
        TestCase {
            name: "dup_one_newest",
            args: &["dup", "-d", "TestFiles", "-D", "ON", "-W"],
            expected_files: &["Images/A1.jpg", "Music/M2.mp3", "Videos/V5.mp4"],
            expected_folders: &[],
            expected_symlinks: &[],
        },
        TestCase {
            name: "dup_all_except_oldest",
            args: &["dup", "-d", "TestFiles", "-D", "AEO", "-W"],
            expected_files: &[
                "Images/A1.jpg",
                "Images/A5.jpg",
                "Music/M1.mp3",
                "Music/M2.mp3",
                "Videos/V1.mp4",
                "Videos/V5.mp4",
            ],
            expected_folders: &[],
            expected_symlinks: &[],
        },
        TestCase {
            name: "dup_all_except_newest",
            args: &["dup", "-d", "TestFiles", "-D", "AEN", "-W"],
            expected_files: &[
                "Images/A2.jpg",
                "Images/A5.jpg",
                "Music/M1.mp3",
                "Music/M5.mp3",
                "Videos/V1.mp4",
                "Videos/V2.mp4",
            ],
            expected_folders: &[],
            expected_symlinks: &[],
        },
        TestCase {
            name: "dup_one_smallest",
            args: &["dup", "-d", "TestFiles", "-D", "OS", "-W"],
            expected_files: &["Images/A1.jpg", "Music/M1.mp3", "Videos/V1.mp4"],
            expected_folders: &[],
            expected_symlinks: &[],
        },
        TestCase {
            name: "dup_one_biggest",
            args: &["dup", "-d", "TestFiles", "-D", "OB", "-W"],
            expected_files: &["Images/A5.jpg", "Music/M5.mp3", "Videos/V5.mp4"],
            expected_folders: &[],
            expected_symlinks: &[],
        },
        TestCase {
            name: "dup_all_except_smallest",
            args: &["dup", "-d", "TestFiles", "-D", "AES", "-W"],
            expected_files: &[
                "Images/A2.jpg",
                "Images/A5.jpg",
                "Music/M2.mp3",
                "Music/M5.mp3",
                "Videos/V2.mp4",
                "Videos/V5.mp4",
            ],
            expected_folders: &[],
            expected_symlinks: &[],
        },
        TestCase {
            name: "dup_all_except_biggest",
            args: &["dup", "-d", "TestFiles", "-D", "AEB", "-W"],
            expected_files: &[
                "Images/A1.jpg",
                "Images/A2.jpg",
                "Music/M1.mp3",
                "Music/M2.mp3",
                "Videos/V1.mp4",
                "Videos/V2.mp4",
            ],
            expected_folders: &[],
            expected_symlinks: &[],
        },
        // ── Music by tags ─────────────────────────────────────────────────────
        TestCase {
            name: "music_tags_one_oldest",
            args: &["music", "-d", "TestFiles", "-D", "OO", "-W"],
            expected_files: &["Music/M5.mp3"],
            expected_folders: &[],
            expected_symlinks: &[],
        },
        TestCase {
            name: "music_tags_one_newest",
            args: &["music", "-d", "TestFiles", "-D", "ON", "-W"],
            expected_files: &["Music/M2.mp3"],
            expected_folders: &[],
            expected_symlinks: &[],
        },
        TestCase {
            name: "music_tags_all_except_oldest",
            args: &["music", "-d", "TestFiles", "-D", "AEO", "-W"],
            expected_files: &["Music/M1.mp3", "Music/M2.mp3", "Music/M3.flac"],
            expected_folders: &[],
            expected_symlinks: &[],
        },
        TestCase {
            name: "music_tags_all_except_newest",
            args: &["music", "-d", "TestFiles", "-D", "AEN", "-W"],
            expected_files: &["Music/M1.mp3", "Music/M3.flac", "Music/M5.mp3"],
            expected_folders: &[],
            expected_symlinks: &[],
        },
        TestCase {
            name: "music_tags_one_smallest",
            args: &["music", "-d", "TestFiles", "-D", "OS", "-W"],
            expected_files: &["Music/M1.mp3"],
            expected_folders: &[],
            expected_symlinks: &[],
        },
        TestCase {
            name: "music_tags_one_biggest",
            args: &["music", "-d", "TestFiles", "-D", "OB", "-W"],
            expected_files: &["Music/M3.flac"],
            expected_folders: &[],
            expected_symlinks: &[],
        },
        TestCase {
            name: "music_tags_all_except_smallest",
            args: &["music", "-d", "TestFiles", "-D", "AES", "-W"],
            expected_files: &["Music/M2.mp3", "Music/M3.flac", "Music/M5.mp3"],
            expected_folders: &[],
            expected_symlinks: &[],
        },
        TestCase {
            name: "music_tags_all_except_biggest",
            args: &["music", "-d", "TestFiles", "-D", "AEB", "-W"],
            expected_files: &["Music/M1.mp3", "Music/M2.mp3", "Music/M5.mp3"],
            expected_folders: &[],
            expected_symlinks: &[],
        },
        // ── Music by content ──────────────────────────────────────────────────
        TestCase {
            name: "music_content_one_oldest",
            args: &["music", "-d", "TestFiles", "-s", "CONTENT", "-l", "2.0", "-D", "OO", "-W"],
            expected_files: &["Music/M5.mp3"],
            expected_folders: &[],
            expected_symlinks: &[],
        },
        TestCase {
            name: "music_content_one_newest",
            args: &["music", "-d", "TestFiles", "-s", "CONTENT", "-l", "2.0", "-D", "ON", "-W"],
            expected_files: &["Music/M2.mp3"],
            expected_folders: &[],
            expected_symlinks: &[],
        },
        TestCase {
            name: "music_content_all_except_oldest",
            args: &["music", "-d", "TestFiles", "-s", "CONTENT", "-l", "2.0", "-D", "AEO", "-W"],
            expected_files: &["Music/M1.mp3", "Music/M2.mp3", "Music/M3.flac"],
            expected_folders: &[],
            expected_symlinks: &[],
        },
        TestCase {
            name: "music_content_all_except_newest",
            args: &["music", "-d", "TestFiles", "-s", "CONTENT", "-l", "2.0", "-D", "AEN", "-W"],
            expected_files: &["Music/M1.mp3", "Music/M3.flac", "Music/M5.mp3"],
            expected_folders: &[],
            expected_symlinks: &[],
        },
        TestCase {
            name: "music_content_one_smallest",
            args: &["music", "-d", "TestFiles", "-s", "CONTENT", "-l", "2.0", "-D", "OS", "-W"],
            expected_files: &["Music/M2.mp3"],
            expected_folders: &[],
            expected_symlinks: &[],
        },
        TestCase {
            name: "music_content_one_biggest",
            args: &["music", "-d", "TestFiles", "-s", "CONTENT", "-l", "2.0", "-D", "OB", "-W"],
            expected_files: &["Music/M3.flac"],
            expected_folders: &[],
            expected_symlinks: &[],
        },
        TestCase {
            name: "music_content_all_except_smallest",
            args: &["music", "-d", "TestFiles", "-s", "CONTENT", "-l", "2.0", "-D", "AES", "-W"],
            expected_files: &["Music/M1.mp3", "Music/M3.flac", "Music/M5.mp3"],
            expected_folders: &[],
            expected_symlinks: &[],
        },
        TestCase {
            name: "music_content_all_except_biggest",
            args: &["music", "-d", "TestFiles", "-s", "CONTENT", "-l", "2.0", "-D", "AEB", "-W"],
            expected_files: &["Music/M1.mp3", "Music/M2.mp3", "Music/M5.mp3"],
            expected_folders: &[],
            expected_symlinks: &[],
        },
        // ── Video ─────────────────────────────────────────────────────────────
        TestCase {
            name: "video_one_oldest",
            args: &["video", "-d", "TestFiles", "-D", "OO", "-W"],
            expected_files: &["Videos/V3.webm"],
            expected_folders: &[],
            expected_symlinks: &[],
        },
        TestCase {
            name: "video_one_newest",
            args: &["video", "-d", "TestFiles", "-D", "ON", "-W"],
            expected_files: &["Videos/V5.mp4"],
            expected_folders: &[],
            expected_symlinks: &[],
        },
        TestCase {
            name: "video_all_except_oldest",
            args: &["video", "-d", "TestFiles", "-D", "AEO", "-W"],
            expected_files: &["Videos/V1.mp4", "Videos/V2.mp4", "Videos/V5.mp4"],
            expected_folders: &[],
            expected_symlinks: &[],
        },
        TestCase {
            name: "video_all_except_newest",
            args: &["video", "-d", "TestFiles", "-D", "AEN", "-W"],
            expected_files: &["Videos/V1.mp4", "Videos/V2.mp4", "Videos/V3.webm"],
            expected_folders: &[],
            expected_symlinks: &[],
        },
        TestCase {
            name: "video_one_smallest",
            args: &["video", "-d", "TestFiles", "-D", "OS", "-W"],
            expected_files: &["Videos/V2.mp4"],
            expected_folders: &[],
            expected_symlinks: &[],
        },
        TestCase {
            name: "video_one_biggest",
            args: &["video", "-d", "TestFiles", "-D", "OB", "-W"],
            expected_files: &["Videos/V3.webm"],
            expected_folders: &[],
            expected_symlinks: &[],
        },
        TestCase {
            name: "video_all_except_smallest",
            args: &["video", "-d", "TestFiles", "-D", "AES", "-W"],
            expected_files: &["Videos/V1.mp4", "Videos/V3.webm", "Videos/V5.mp4"],
            expected_folders: &[],
            expected_symlinks: &[],
        },
        TestCase {
            name: "video_all_except_biggest",
            args: &["video", "-d", "TestFiles", "-D", "AEB", "-W"],
            expected_files: &["Videos/V1.mp4", "Videos/V2.mp4", "Videos/V5.mp4"],
            expected_folders: &[],
            expected_symlinks: &[],
        },
    ]
}
