import { Button } from "std-widgets.slint";
import { Callabler } from "callabler.slint";
import { Translations } from "translations.slint";
import { FontSizes } from "fonts.slint";

export component About inherits VerticalLayout {
    preferred-height: 300px;
    preferred-width: 400px;

    img := Image {
        source: @image-url("../icons/krokiet_logo_flag_name_vertical.png"); // TODO simplify svg, to be able to use here svg version with text
        image-fit: ImageFit.contain;
    }

    Text {
        text: "11.0.0";
        horizontal-alignment: center;
        font-size: max(min(img.width / 20, FontSizes.header), FontSizes.small);
    }

    VerticalLayout {
        spacing: 10px;
        padding-bottom: 10px;
        Text {
            text: "2020 - 2026  Rafał Mikrut(qarmin)";
            horizontal-alignment: center;
            font-size: FontSizes.header;
        }

        Text {
            text <=> Translations.motto_text;
            horizontal-alignment: center;
            font-size: FontSizes.normal;
        }

        Text {
            text <=> Translations.unicorn_text;
            horizontal-alignment: center;
            font-size: FontSizes.normal;
        }
    }

    HorizontalLayout {
        spacing: 5px;
        Button {
            text <=> Translations.repository_text;
            clicked => {
                Callabler.open_link("https://github.com/qarmin/czkawka");
            }
        }

        Button {
            text <=> Translations.instruction_text;
            clicked => {
                Callabler.open_link("https://github.com/qarmin/czkawka/blob/master/instructions/Instruction.md");
            }
        }

        Button {
            text <=> Translations.donation_text;
            clicked => {
                Callabler.open_link("https://github.com/sponsors/qarmin");
            }
        }

        Button {
            text <=> Translations.translation_text;
            clicked => {
                Callabler.open_link("https://crwd.in/czkawka");
            }
        }
    }
}
