import { Button, VerticalBox , HorizontalBox, TabWidget, ListView, StandardListView, StandardTableView, CheckBox, ScrollView, LineEdit, SpinBox, ComboBox, TextEdit, Slider} from "std-widgets.slint";
import { Settings } from "settings.slint";
import { Callabler } from "callabler.slint";
import { GuiState } from "gui_state.slint";

export component About inherits VerticalLayout {
    preferred-height: 300px;
    preferred-width: 400px;

    img := Image {
        source: @image-url("../icons/logo.png");
        image-fit: ImageFit.contain;
    }
    Text {
        text: "8.0.0";
        horizontal-alignment: center;
        font-size: max(min(img.width / 20, 17px), 10px);
    }
    
    VerticalLayout {
        spacing: 10px;
        padding-bottom: 10px;
        Text {
            text: "2020 - 2024  Rafał Mikrut(qarmin)";
            horizontal-alignment: center;
            font-size: 15px;
        }
        Text {
            text: "This program is free to use and will always be.\nSee the The MIT/GPL License for details.";
            horizontal-alignment: center;
            font-size: 13px;
        }
        Text {
            text: "You may not look at unicorn, but unicorn always looks at you.";
            horizontal-alignment: center;
            font-size: 13px;
        }
    }
    
    HorizontalLayout {
        spacing: 5px;
        Button {
            text: "Repository";
            clicked => {
                Callabler.open_link("https://github.com/qarmin/czkawka");
            }
        }
        Button {
            text: "Instruction";
            clicked => {
                Callabler.open_link("https://github.com/qarmin/czkawka/blob/master/instructions/Instruction.md");
            }
        }
        Button {
            text: "Donation";
            clicked => {
                Callabler.open_link("https://github.com/sponsors/qarmin");
            }
        }
        Button {
            text: "Translation";
            clicked => {
                Callabler.open_link("https://crwd.in/czkawka");
            }
        }
    }
}