import { StyleMetrics, Palette } from "std-widgets.slint";

export global ColorPalette {
    in-out property <bool> dark_scheme: Palette.color-scheme == ColorScheme.dark;
    // Tabs at left side
    in-out property <color> tab_selected_color: dark_scheme ? #353535 : #5e5e5e;
    in-out property <color> tab_hovered_color: dark_scheme ? #49494926 : #80808014;
    // ListView
    in-out property <color> list_view_normal_color: dark_scheme ? #222222 : #dddddd;
    in-out property <color> list_view_normal_header_color: dark_scheme ? #111111 : #888888;
    in-out property <color> list_view_normal_selected_header: dark_scheme ? #444444 : #cccccc;
    // Popup
    in-out property <color> popup_background: dark_scheme ? #353535 : #5e5e5e;
}
