import { StyleMetrics } from "std-widgets.slint";

export global ColorPalette {
    // Tabs at left side
    in-out property <color> tab_selected_color: StyleMetrics.dark-color-scheme ? #353535 : #5e5e5e;
    in-out property <color> tab_hovered_color: StyleMetrics.dark-color-scheme ? #49494926 : #80808014;
    // ListView
    in-out property <color> list_view_normal_color: StyleMetrics.dark-color-scheme ? #222222 : #dddddd;
    in-out property <color> list_view_normal_header_color: StyleMetrics.dark-color-scheme ? #111111 : #888888;
    in-out property <color> list_view_normal_selected_header: StyleMetrics.dark-color-scheme ? #444444 : #cccccc;
    // Popup
    in-out property <color> popup_background: StyleMetrics.dark-color-scheme ? #353535 : #5e5e5e;
}
