export enum CurrentTab {
    DuplicateFiles,
    EmptyFolders,
    BigFiles,
    EmptyFiles,
    TemporaryFiles,
    SimilarImages,
    SimilarVideos,
    SimilarMusic,
    InvalidSymlinks,
    BrokenFiles,
    BadExtensions,
    Settings,
    About
}

export enum TypeOfOpenedItem {
    CurrentItem,
    ParentItem,
}

export struct ProgressToSend {
    current_progress: int,
    current_progress_size: int,
    all_progress: int,
    step_name: string,
}

export struct MainListModel {
    checked: bool,
    header_row: bool,
    filled_header_row: bool,
    selected_row: bool,
    val_str: [string],
    val_int: [int]
}

export enum BottomPanelVisibility {
    NotVisible,
    TextErrors,
    Directories
}

export struct IncludedDirectoriesModel {
    path: string,
    referenced_folder: bool,
    selected_row: bool,
}

export struct ExcludedDirectoriesModel {
    path: string,
    selected_row: bool,
}

export enum SelectMode {
    SelectAll,
    UnselectAll,
    InvertSelection,
    SelectTheBiggestSize,
    SelectTheBiggestResolution,
    SelectTheSmallestSize,
    SelectTheSmallestResolution,
    SelectNewest,
    SelectOldest,
}

export struct SelectModel {
    data: SelectMode,
    name: string
}