export enum ActiveTab {
    DuplicateFiles,
    EmptyFolders,
    BigFiles,
    EmptyFiles,
    TemporaryFiles,
    SimilarImages,
    SimilarVideos,
    SimilarMusic,
    InvalidSymlinks,
    BrokenFiles,
    BadExtensions,
    ExifRemover,
    VideoOptimizer,
    Settings,
    About
}

export enum PopupRequest {
    Delete,
    Move,
    CleanExif,
    OptimizeVideo,
    Rename,
    Symlink,
    Hardlink,
    Save
}

export enum SortColumnMode {
    None, // None is default mode, is set when starting scan and cannot be restored by user
    Descending,
    Ascending
}

export enum TypeOfOpenedItem {
    CurrentItem,
    ParentItem
}

export struct ProgressToSend {
    current_progress: int,
    current_progress_size: int,
    all_progress: int,
    step_name: string,
}

export struct MainListModel {
    checked: bool,
    header_row: bool,
    filled_header_row: bool,
    selected_row: bool,
    val_str: [string],
    val_int: [int]
}

export enum BottomPanelVisibility {
    NotVisible,
    TextErrors,
    Directories
}

export struct IncludedPathsModel {
    path: string,
    referenced_path: bool,
    selected_row: bool,
}

export struct ExcludedPathsModel {
    path: string,
    selected_row: bool,
}

export enum SelectMode {
    SelectAll,
    UnselectAll,
    InvertSelection,
    SelectTheBiggestSize,
    SelectTheBiggestResolution,
    SelectTheSmallestSize,
    SelectTheSmallestResolution,
    SelectNewest,
    SelectOldest,
}

export struct SelectModel {
    data: SelectMode,
    name: string
}

export enum SortMode {
    FullName,
    Selection,
    Reverse
}

export struct SortModel {
    data: SortMode,
    name: string
}

export struct CacheCleaningProgress {
    current_cache_file: int,
    total_cache_files: int,
    current_file_name: string,
    checked_entries: int,
    all_entries: int,
}

export struct CacheCleaningResult {
    processed_files_text: string,
    entries_stats_text: string,
    size_stats_text: string,
    time_text: string,
    errors_count: int,
    errors: string,
}
