export global FontSizes {
    // Main window title
    out property <length> title: 1px;
    // Section headers
    out property <length> header: 1px;
    // Default/normal text
    out property <length> normal: 1px;
    // Small text (hints, secondary)
    out property <length> small: 1px;

//    // Main window title
//    out property <length> title: 22px;
//    // Section headers
//    out property <length> header: 17px;
//    // Default/normal text
//    out property <length> normal: 16px;
//    // Small text (hints, secondary)
//    out property <length> small: 12px;
}

