import { HorizontalBox, LineEdit, Palette, VerticalBox } from "std-widgets.slint";
import { LeftSidePanel } from "left_side_panel.slint";
import { MainList } from "main_lists.slint";
import { ActiveTab, MainListModel, ProgressToSend } from "common.slint";
import { ActionButtons } from "action_buttons.slint";
import { Progress } from "progress.slint";
import { Settings } from "settings.slint";
import { Callabler } from "callabler.slint";
import { BottomPanel } from "bottom_panel.slint";
import { GuiState } from "gui_state.slint";
import { Preview } from "preview.slint";
import { PopupNewDirectories } from "popup_new_directories.slint";
import { PopupDelete } from "popup_delete.slint";
import { PopupMoveFolders } from "popup_move_folders.slint";
import { PopupSelectResults } from "popup_select_results.slint";
import { PopupRenameFiles } from "popup_rename_files.slint";
import { PopupSave } from "popup_save.slint";
import { PopupSortResults } from "popup_sort.slint";
import { PopupActionConfirm } from "popup_action_confirm.slint";
import { ToolSettings } from "tool_settings.slint";
import { Translations } from "translations.slint";

export {Settings, Callabler, GuiState, Translations, Palette}

export component MainWindow inherits Window {
    callback scan_stopping;
    callback scan_starting(ActiveTab);
    callback folder_choose_requested(bool);
    callback scan_ended(string);
    callback show_move_folders_dialog(string);
    callback folders_move_choose_requested();
    callback reset_selection();
    callback initialize_popup_sizes();
    callback processing_ended(string);

    callback delete_popup_dialog_show_requested();
    callback delete_popup_dialog_configured();

    title <=> Translations.main_window_title_text;

    min-width: 300px;
    preferred-width: 800px;
    min-height: 300px;
    preferred-height: 600px;
    in-out property <string> text_summary_text: "";
    in-out property <bool> stop_requested: false;
    in-out property <bool> scanning: false;
    in-out property <bool> processing: false;
    in-out property <ProgressToSend> progress_datas: {
        current_progress: 15,
        all_progress: 20,
        step_name: "Cache",
    };
    in-out property <[MainListModel]> duplicate_files_model: [];
    in-out property <[MainListModel]> empty_folder_model: [];
    in-out property <[MainListModel]> big_files_model: [];
    in-out property <[MainListModel]> empty_files_model: [];
    in-out property <[MainListModel]> temporary_files_model: [];
    in-out property <[MainListModel]> similar_images_model: [];
    in-out property <[MainListModel]> similar_videos_model: [];
    in-out property <[MainListModel]> similar_music_model: [];
    in-out property <[MainListModel]> invalid_symlinks_model: [];
    in-out property <[MainListModel]> broken_files_model: [];
    in-out property <[MainListModel]> bad_extensions_model: [];
    in-out property <[MainListModel]> exif_finder_model: [];
    in-out property <[MainListModel]> iv_optimizer_model: [];

    VerticalBox {
        HorizontalBox {
            vertical-stretch: 1.0;
            preferred-height: 300px;
            LeftSidePanel {
                horizontal-stretch: 0.0;
                changed_active_tab() => {
                    GuiState.preview_visible = false;
                    main_list.changed_active_tab();
                }
            }

            VerticalLayout {
                horizontal-stretch: 1.0;
                min_width: 300px;
                Rectangle {
                    vertical-stretch: 1.0;
                    main_list := MainList {
                        x: 0;
                        width: preview_or_tool_settings.visible ? parent.width / 2 : parent.width;
                        height: parent.height;
                        horizontal-stretch: 0.5;
                        working: root.scanning || root.processing;
                        duplicate_files_model <=> root.duplicate_files_model;
                        empty_folder_model <=> root.empty_folder_model;
                        big_files_model <=> root.big_files_model;
                        empty_files_model <=> root.empty_files_model;
                        temporary_files_model <=> root.temporary_files_model;
                        similar_images_model <=> root.similar_images_model;
                        similar_videos_model <=> root.similar_videos_model;
                        similar_music_model <=> root.similar_music_model;
                        invalid_symlinks_model <=> root.invalid_symlinks_model;
                        broken_files_model <=> root.broken_files_model;
                        bad_extensions_model <=> root.bad_extensions_model;
                        exif_finder_model <=> root.exif_finder_model;
                        iv_optimizer_model <=> root.iv_optimizer_model;
                    }

                    preview_or_tool_settings := Rectangle {
                        visible: (GuiState.preview_visible || tool_settings.visible) && GuiState.is_tool_tab_active;
                        height: parent.height;
                        x: parent.width / 2;
                        width: self.visible ? parent.width / 2 : 0;
                        Preview {
                            height: parent.height;
                            width: parent.width;
                            visible: GuiState.preview_visible && !tool_settings.visible;
                            source: GuiState.preview_image;
                            image-fit: ImageFit.contain;
                        }

                        tool_settings := ToolSettings {
                            height: parent.height;
                            width: parent.width;
                            visible: GuiState.visible_tool_settings && GuiState.available_subsettings;
                        }
                    }
                }

                if root.scanning || root.processing: Progress {
                    horizontal-stretch: 0.0;
                    progress_datas <=> root.progress_datas;
                }
            }
        }

        action_buttons := ActionButtons {
            duplicate_files_model <=> root.duplicate_files_model;
            empty_folder_model <=> root.empty_folder_model;
            big_files_model <=> root.big_files_model;
            empty_files_model <=> root.empty_files_model;
            temporary_files_model <=> root.temporary_files_model;
            similar_images_model <=> root.similar_images_model;
            similar_videos_model <=> root.similar_videos_model;
            similar_music_model <=> root.similar_music_model;
            invalid_symlinks_model <=> root.invalid_symlinks_model;
            broken_files_model <=> root.broken_files_model;
            bad_extensions_model <=> root.bad_extensions_model;
            exif_finder_model <=> root.exif_finder_model;
            iv_optimizer_model <=> root.iv_optimizer_model;

            vertical-stretch: 0.0;
            scanning <=> root.scanning;
            processing <=> root.processing;
            stop_requested <=> root.stop_requested;
            scan_stopping => {
                text_summary_text = Translations.stopping_scan_text;
                root.scan_stopping();
            }
            scan_starting(item) => {
                text_summary_text = Translations.searching_text;
                root.scan_starting(item);
                main_list.scan_started(); // Need to clear sorting state
            }
            show_select_popup(x_offset, y_offset) => {
                select_popup_window.x_offset = x_offset;
                select_popup_window.y_offset = y_offset;
                select_popup_window.show_popup();
            }
            request_folder_to_move => {
                folders_move_choose_requested();
            }
            show_remove_popup => {
                delete_popup_dialog_show_requested();
            }
            show_rename_popup => {
                rename_popup_window.show_popup();
            }
            show_clean_popup => {
                clean_popup_window.show_popup();
            }
            show_optimize_popup => {
                optimize_popup_window.show_popup();
            }
            show_hardlink_popup => {
                hardlink_popup_window.show_popup();
            }
            show_softlink_popup => {
                softlink_popup_window.show_popup();
            }
            show_save_popup => {
                save_popup_window.show_popup();
            }
            show_sort_popup(x_offset, y_offset) => {
                sort_popup_window.x_offset = x_offset;
                sort_popup_window.y_offset = y_offset;
                sort_popup_window.show_popup();
            }
        }

        HorizontalLayout {
            spacing: 5px;
            text_summary := LineEdit {
                text: text_summary_text;
                read-only: true;
            }

            Text {
                text: "Krokiet\n10.0.0";
                vertical-alignment: center;
                horizontal-alignment: center;
            }
        }

        bottom_panel := BottomPanel {
            bottom_panel_visibility <=> action_buttons.bottom_panel_visibility;
            vertical-stretch: 0.0;
            folder_choose_requested(included_directories) => {
                root.folder_choose_requested(included_directories)
            }
            show_manual_add_dialog(included_directories) => {
                GuiState.choosing_include_directories = included_directories;
                new_directory_popup_window.show_popup()
            }
        }
    }

    new_directory_popup_window := PopupNewDirectories {
        height: root.height;
        width: root.width;

        x: parent.x + (root.width - self.popup_width) / 2.0;
        y: parent.y + (parent.height - self.popup_height) / 2.0;
    }

    select_popup_window := PopupSelectResults {
        property <length> x_offset: 0;
        property <length> y_offset: 0;
        x: parent.x + x_offset - self.item_width / 2.0;
        y: parent.y + y_offset - self.all_items_height - 5px;
        height: root.height;
        width: root.width;
    }

    delete_popup_window := PopupDelete {
        height: root.height;
        width: root.width;

        x: parent.x + (root.width - self.popup_width) / 2.0;
        y: parent.y + (parent.height - self.popup_height) / 2.0;
    }

    move_popup_window := PopupMoveFolders {
        height: root.height;
        width: root.width;

        x: parent.x + (root.width - self.popup_width) / 2.0;
        y: parent.y + (parent.height - self.popup_height) / 2.0;
    }

    rename_popup_window := PopupRenameFiles {
        height: root.height;
        width: root.width;

        x: parent.x + (root.width - self.popup_width) / 2.0;
        y: parent.y + (parent.height - self.popup_height) / 2.0;
    }

    save_popup_window := PopupSave {
        height: root.height;
        width: root.width;

        x: parent.x + (root.width - self.popup_width) / 2.0;
        y: parent.y + (parent.height - self.popup_height) / 2.0;
    }

    sort_popup_window := PopupSortResults {
        property <length> x_offset: 0;
        property <length> y_offset: 0;
        x: parent.x + x_offset - self.item_width / 2.0;
        y: parent.y + y_offset - self.all_items_height - 5px;
        height: root.height;
        width: root.width;
    }

    clean_popup_window := PopupActionConfirm {
        height: root.height;
        width: root.width;
        title_text: Translations.clean_text;
        confirmation_text: Translations.clean_confirmation_text;

        x: parent.x + (root.width - self.popup_width) / 2.0;
        y: parent.y + (parent.height - self.popup_height) / 2.0;

        action_confirmed => {
            Callabler.clean_items();
        }
    }

    optimize_popup_window := PopupActionConfirm {
        height: root.height;
        width: root.width;
        title_text: Translations.optimize_text;
        confirmation_text: Translations.optimize_confirmation_text;

        x: parent.x + (root.width - self.popup_width) / 2.0;
        y: parent.y + (parent.height - self.popup_height) / 2.0;

        action_confirmed => {
            Callabler.optimize_items();
        }
    }

    hardlink_popup_window := PopupActionConfirm {
        height: root.height;
        width: root.width;
        title_text: Translations.hardlink_text;
        confirmation_text: Translations.hardlink_confirmation_text;

        x: parent.x + (root.width - self.popup_width) / 2.0;
        y: parent.y + (parent.height - self.popup_height) / 2.0;

        action_confirmed => {
            Callabler.hardlink_items();
        }
    }

    softlink_popup_window := PopupActionConfirm {
        height: root.height;
        width: root.width;
        title_text: Translations.softlink_text;
        confirmation_text: Translations.softlink_confirmation_text;

        x: parent.x + (root.width - self.popup_width) / 2.0;
        y: parent.y + (parent.height - self.popup_height) / 2.0;

        action_confirmed => {
            Callabler.softlink_items();
        }
    }

    show_move_folders_dialog(folder_name) => {
        move_popup_window.folder_name = folder_name;
        move_popup_window.show_popup();
    }

    scan_ended(scan_text) => {
        text_summary_text = scan_text;
        root.scanning = false;
        root.stop_requested = false;
    }

    processing_ended(process_text) => {
        text_summary_text = process_text;
        root.processing = false;
        root.stop_requested = false;
    }

    reset_selection => {
        main_list.reset_selection();
    }

    initialize_popup_sizes => {
        sort_popup_window.show_popup();
        sort_popup_window.close_popup();
        select_popup_window.show_popup();
        select_popup_window.close_popup();
    }

    delete_popup_dialog_configured => {
        delete_popup_window.show_popup();
    }
}
