import { Button, VerticalBox ,TextEdit, HorizontalBox, TabWidget, ListView, StandardListView, StandardTableView, CheckBox, LineEdit} from "std-widgets.slint";
import {CurrentTab, ProgressToSend} from "common.slint";
import { ActionButtons } from "action_buttons.slint";
import { Progress } from "progress.slint";
import {MainListModel, SelectMode, SelectModel} from "common.slint";
import {Callabler} from "callabler.slint";
import { Translations } from "translations.slint";
import { PopupBase } from "popup_base.slint";
import { PopupCenteredText } from "popup_centered_text.slint";

export component PopupSave inherits Rectangle {
    out property <length> popup_width: 500px;
    out property <length> popup_height: 150px;
    callback show_popup();

    popup_window := PopupBase {
        width: popup_width;
        height: popup_height;
        title_text <=> Translations.popup_save_title_text;

        VerticalLayout {
            PopupCenteredText {
                text: Translations.popup_save_message_text + "\n\n" + Translations.are_you_want_to_continue_text;
            }
        }

        ok_clicked => {
            Callabler.save_results();
        }
    }

    show_popup() => {
        popup_window.show();
    }
}

