import { Button, VerticalBox ,TextEdit, HorizontalBox, TabWidget, ListView, StandardListView, StandardTableView, CheckBox, LineEdit} from "std-widgets.slint";
import {SelectableTableView} from "selectable_tree_view.slint";
import {LeftSidePanel} from "left_side_panel.slint";
import {MainList} from "main_lists.slint";
import {CurrentTab, ProgressToSend} from "common.slint";
import { ActionButtons } from "action_buttons.slint";
import { Progress } from "progress.slint";
import {MainListModel, SelectMode, SelectModel} from "common.slint";
import {Settings} from "settings.slint";
import {Callabler} from "callabler.slint";
import { BottomPanel } from "bottom_panel.slint";
import {ColorPalette} from "color_palette.slint";
import {GuiState} from "gui_state.slint";
import { Preview } from "preview.slint";

export component PopupDelete inherits Rectangle {
    out property <length> popup_width: 350px;
    out property <length> popup_height: 150px;
    callback show_popup();

    popup_window := PopupWindow {
        width: popup_width;
        height: popup_height;

        close-on-click: true;
        Rectangle {
            width: parent.width;
            height: parent.height;
            border-radius: 5px;
            background: ColorPalette.popup_background;
            VerticalLayout {
                Text {
                    vertical-stretch: 0.0;
                    text: "Delete items";
                    vertical-alignment: center;
                    horizontal-alignment: center;
                    font-size: 13px;
                    padding: 10px;
                }
                Text {
                    vertical-stretch: 1.0;
                    text: "Are you sure you want to delete the selected items?";
                    vertical-alignment: center;
                    horizontal-alignment: center;
                    font-size: 13px;
                    padding: 10px;
                }
                HorizontalLayout {
                    Button {
                        text: "Yes";
                        clicked => {
                            popup_window.close();
                            Callabler.delete_selected_items();
                        }
                    }
                    Rectangle {

                    }
                    Button {
                        text: "No";
                        clicked => {
                            popup_window.close();
                        }
                    }
                }
            }
        }
    }

    show_popup() => {
        popup_window.show();
    }
}