import { Button, VerticalBox ,TextEdit, HorizontalBox, TabWidget, ListView, StandardListView, StandardTableView, CheckBox, LineEdit} from "std-widgets.slint";
import {CurrentTab, ProgressToSend} from "common.slint";
import { ActionButtons } from "action_buttons.slint";
import { Progress } from "progress.slint";
import {MainListModel, SelectMode, SelectModel} from "common.slint";
import {Callabler} from "callabler.slint";
import { Translations } from "translations.slint";
import { PopupBase } from "popup_base.slint";
import { PopupCenteredText } from "popup_centered_text.slint";
import {GuiState} from "gui_state.slint";

export component PopupNewDirectories inherits Rectangle {
    out property <length> popup_width: 350px;
    out property <length> popup_height: 150px;
    callback show_popup();

    property <bool> included_directories;
    private property <string> text_data;

    popup_window := PopupBase {
        width: popup_width;
        height: popup_height;
        title_text <=> Translations.popup_new_directories_title_text;
        enabled_ok_button: text_data != "";

        VerticalLayout {
            TextEdit {
                vertical-stretch: 1.0;
                text <=> text_data;
            }
        }

        ok_clicked => {
            Callabler.added_manual_directories(GuiState.choosing_include_directories, text_data);
        }
    }

    show_popup() => {
        popup_window.show();
    }
}
