import { Callabler } from "callabler.slint";
import { Translations } from "translations.slint";
import { PopupBase } from "popup_base.slint";
import { PopupCenteredText } from "popup_centered_text.slint";

export component PopupTrash inherits Rectangle {
    out property <length> popup_width: 400px;
    out property <length> popup_height: 200px;
    callback show_popup();

    popup_window := PopupBase {
        width: popup_width;
        height: popup_height;
        title_text <=> Translations.trash_text;

        VerticalLayout {
            PopupCenteredText {
                text <=> Translations.trash_confirmation_text;
            }
        }

        ok_clicked => {
            Callabler.trash_selected_items();
        }
    }

    show_popup() => {
        popup_window.show();
    }
}
