import { PopupBase } from "popup_base.slint";
import { Translations } from "translations.slint";
import { Button, CheckBox, ComboBox, LineEdit, Slider } from "std-widgets.slint";
import { Settings } from "settings.slint";
import { PopupCenteredText } from "popup_centered_text.slint";
import { ColorPalette } from "color_palette.slint";
import { FontSizes } from "fonts.slint";
import { Callabler } from "callabler.slint";

export component PopupReencodeVideo inherits Rectangle {
    in-out property <string> title_text;

    callback action_confirmed();

    out property <length> popup_width: 440px;
    out property <length> popup_height: 560px;
    callback show_popup();

    popup_window := PopupBase {
        width: popup_width;
        height: popup_height;
        title_text <=> root.title_text;

        VerticalLayout {
            spacing: 8px;

            Rectangle { height: 8px; }

            HorizontalLayout {
                spacing: 0px;

                Rectangle { width: 8px; }

                VerticalLayout {
                    spacing: 8px;

                    PopupCenteredText { text: Translations.optimize_confirmation_text; }

                    HorizontalLayout {
                        spacing: 5px;
                        Text { text: Translations.subsettings_video_optimizer_video_codec_text; vertical_alignment: TextVerticalAlignment.center; }
                        ComboBox {
                            model <=> Settings.video_optimizer_sub_video_codec_config;
                            current_index <=> Settings.video_optimizer_sub_video_codec_index;
                            current_value <=> Settings.video_optimizer_sub_video_codec_value;
                        }
                    }

                    HorizontalLayout {
                        spacing: 5px;
                        Text { text: Translations.subsettings_video_optimizer_video_quality_text; vertical_alignment: TextVerticalAlignment.center; }
                        Slider { minimum: 0.0; maximum: 51.0; value <=> Settings.popup_reencode_video_quality; }
                        Text {
                            text: Math.round(Settings.popup_reencode_video_quality) + " / 51";
                            vertical_alignment: TextVerticalAlignment.center;
                            min-width: 50px;
                        }
                    }

                    Text {
                        text: Translations.optimize_crf_hint_text;
                        font-size: FontSizes.small;
                        color: ColorPalette.hint_color;
                        wrap: TextWrap.word-wrap;
                    }

                    HorizontalLayout {
                        spacing: 5px;
                        Text { text: Translations.subsettings_video_optimizer_noise_reduction_text; vertical_alignment: TextVerticalAlignment.center; }
                        ComboBox {
                            model <=> Settings.video_optimizer_sub_noise_reduction;
                            current_index <=> Settings.video_optimizer_sub_noise_reduction_index;
                            current_value <=> Settings.video_optimizer_sub_noise_reduction_value;
                            enabled: !Settings.video_optimizer_sub_use_custom_command;
                        }
                    }

                    if Settings.video_optimizer_sub_noise_reduction_index != 0: HorizontalLayout {
                        spacing: 5px;
                        Text { text: Translations.subsettings_video_optimizer_noise_reduction_strength_text; vertical_alignment: TextVerticalAlignment.center; }
                        Slider {
                            minimum: 1;
                            maximum: 10;
                            value <=> Settings.video_optimizer_sub_noise_reduction_strength;
                            enabled: !Settings.video_optimizer_sub_use_custom_command;
                        }
                        Text {
                            text: Math.round(Settings.video_optimizer_sub_noise_reduction_strength) + " / 10";
                            vertical_alignment: TextVerticalAlignment.center;
                            min-width: 40px;
                        }
                    }

                    if Settings.video_optimizer_sub_noise_reduction_index != 0: Text {
                        text: Translations.optimize_noise_reduction_strength_hint_text;
                        font-size: FontSizes.small;
                        color: ColorPalette.hint_color;
                        wrap: TextWrap.word-wrap;
                    }

                    Text {
                        text: Translations.optimize_noise_reduction_hint_text;
                        font-size: FontSizes.small;
                        color: ColorPalette.hint_color;
                        wrap: TextWrap.word-wrap;
                    }

                    CheckBox { text: Translations.optimize_fail_if_bigger_text; checked <=> Settings.popup_reencode_video_fail_if_bigger; }
                    CheckBox { text: Translations.optimize_overwrite_files_text; checked <=> Settings.popup_reencode_video_overwrite_files; }

                    CheckBox { text: Translations.optimize_limit_video_size_text; checked <=> Settings.popup_reencode_video_limit_video_size; }

                    HorizontalLayout {
                        spacing: 5px;
                        Text { text: Translations.optimize_max_width_text; vertical_alignment: TextVerticalAlignment.center; }
                        LineEdit { text <=> Settings.popup_reencode_video_max_width; enabled: Settings.popup_reencode_video_limit_video_size; }
                        Text { text: Translations.optimize_max_height_text; vertical_alignment: TextVerticalAlignment.center; }
                        LineEdit { text <=> Settings.popup_reencode_video_max_height; enabled: Settings.popup_reencode_video_limit_video_size; }
                    }

                    CheckBox { text: Translations.subsettings_video_optimizer_use_custom_command_text; checked <=> Settings.video_optimizer_sub_use_custom_command; }

                    if Settings.video_optimizer_sub_use_custom_command: VerticalLayout {
                        spacing: 5px;

                        Text {
                            text: Translations.subsettings_video_optimizer_custom_command_hint_text;
                            font-size: FontSizes.small;
                            color: ColorPalette.hint_color;
                            wrap: TextWrap.word-wrap;
                        }

                        HorizontalLayout {
                            spacing: 5px;

                            LineEdit {
                                text <=> Settings.video_optimizer_sub_custom_command;
                                font-size: FontSizes.normal;
                                horizontal-stretch: 1.0;
                            }

                            Button {
                                text: Translations.subsettings_video_optimizer_generate_template_text;
                                clicked => { Callabler.generate_video_optimizer_template(); }
                            }
                        }
                    }

                    Rectangle { height: 10px; }
                }

                Rectangle { width: 8px; }
            }
        }

        ok_clicked => {
            root.action_confirmed();
        }

        cancel_clicked => {
        }
    }

    show_popup() => { popup_window.show(); }
}
