import { PopupBase } from "popup_base.slint";
import { PopupCenteredText } from "popup_centered_text.slint";

export component PopupActionConfirm inherits Rectangle {
    in-out property <string> title_text;
    in-out property <string> confirmation_text;
    callback action_confirmed();

    out property <length> popup_width: 350px;
    out property <length> popup_height: 150px;
    callback show_popup();

    popup_window := PopupBase {
        width: popup_width;
        height: popup_height;
        title_text <=> root.title_text;

        VerticalLayout {
            PopupCenteredText {
                text <=> root.confirmation_text;
            }
        }

        ok_clicked => {
            root.action_confirmed();
        }
    }

    show_popup() => {
        popup_window.show();
    }
}
