import { Button, CheckBox, ComboBox, LineEdit, ScrollView, Slider } from "std-widgets.slint";
import { Settings } from "settings.slint";
import { Callabler } from "callabler.slint";
import { GuiState } from "gui_state.slint";
import { Translations } from "translations.slint";
import { ColorPalette } from "color_palette.slint";
import { FontSizes } from "fonts.slint";

// TODO use Spinbox instead LineEdit {} to be able to set only numbers

global SettingsSize {
    out property <length> item_height: 30px;
}

export component TextComponent inherits HorizontalLayout {
    in-out property <string> model;
    in property <string> name;
    spacing: 5px;
    Text {
        font-size: FontSizes.normal;
        horizontal-stretch: 0.0;
        vertical-alignment: TextVerticalAlignment.center;
        text: name;
    }

    LineEdit {
        horizontal-stretch: 1.0;
        height: SettingsSize.item_height;
        text <=> model;
        font-size: FontSizes.normal;
    }
}

component CheckBoxComponent inherits HorizontalLayout {
    in-out property <bool> model;
    in property <string> name;
    in-out property <bool> enabled: true;
    callback toggled();
    spacing: 5px;
    CheckBox {
        horizontal-stretch: 1.0;
        height: SettingsSize.item_height;
        checked <=> model;
        enabled <=> enabled;
        text: name;
        toggled => {
            root.toggled();
        }
    }
    Rectangle { }
}

component ThreadSliderComponent inherits HorizontalLayout {
    in-out property <float> minimum_number;
    in-out property <float> maximum_number;
    in-out property <string> name;
    spacing: 5px;

    callback changed();
    Text {
        text <=> name;
        vertical-alignment: TextVerticalAlignment.center;
        height: SettingsSize.item_height;
        font-size: FontSizes.normal;
    }

    slider := Slider {
        enabled: true;
        height: SettingsSize.item_height;
        minimum: minimum_number;
        maximum <=> maximum_number;
        value <=> Settings.thread_number;
        changed => root.changed();
    }

    Text {
        height: SettingsSize.item_height;
        vertical-alignment: TextVerticalAlignment.center;
        text: round(slider.value) == 0 ? ("All (" + GuiState.maximum_threads + "/" + GuiState.maximum_threads + ")") : (round(slider.value) + "/" + GuiState.maximum_threads);
        font-size: FontSizes.normal;
    }
}

component ApplicationScaleComponent inherits HorizontalLayout {
    spacing: 5px;
    in-out property <string> name;
    callback changed();
    Text {
        text <=> name;
        vertical-alignment: TextVerticalAlignment.center;
        height: SettingsSize.item_height;
        font-size: FontSizes.normal;
    }
    slider := Slider {
        minimum: 0.5;
        maximum: 3.0;
        step: 0.01;
        value <=> Settings.manual_application_scale;
        height: SettingsSize.item_height;
        changed => root.changed();
    }
    Text {
        height: SettingsSize.item_height;
        vertical-alignment: TextVerticalAlignment.center;
        text: (round(slider.value * 100.0) / 100.0);
        font-size: FontSizes.normal;
    }
}

component MinMaxSizeComponent inherits HorizontalLayout {
    spacing: 20px;
    Text {
        horizontal-stretch: 0.0;
        text <=> Translations.settings_file_size_text;
        vertical-alignment: TextVerticalAlignment.center;
        font-size: FontSizes.normal;
    }

    HorizontalLayout {
        spacing: 5px;
        horizontal-stretch: 1.0;
        Text {
            text <=> Translations.settings_minimum_file_size_text;
            vertical-alignment: TextVerticalAlignment.center;
            font-size: FontSizes.normal;
        }

        LineEdit {
            height: SettingsSize.item_height;
            text <=> Settings.minimum_file_size;
            font-size: FontSizes.normal;
        }

        Text {
            text <=> Translations.settings_maximum_file_size_text;
            vertical-alignment: TextVerticalAlignment.center;
            font-size: FontSizes.normal;
        }

        LineEdit {
            height: SettingsSize.item_height;
            text <=> Settings.maximum_file_size;
            font-size: FontSizes.normal;
        }
    }
}

component Presets inherits Rectangle {
    property <bool> edit_name;
    property <string> current_index;
    if !edit_name: HorizontalLayout {
        spacing: 5px;
        Text {
            text <=> Translations.settings_current_preset_text;
            vertical-alignment: TextVerticalAlignment.center;
            font-size: FontSizes.normal;
        }

        combo_box := ComboBox {
            current-index <=> Settings.settings_preset_idx;
            model: Settings.settings_presets;
            selected(item) => {
                Settings.settings_preset_idx = self.current_index;
                Callabler.changed_settings_preset();
            }
        }

        Button {
            text <=> Translations.settings_edit_name_text;
            clicked => {
                root.edit_name = !root.edit_name;
            }
        }
    }
    if edit_name: HorizontalLayout {
        spacing: 5px;
        Text {
            text: Translations.settings_choose_name_for_prefix_text + (Settings.settings_preset_idx + 1);
            vertical-alignment: TextVerticalAlignment.center;
            font-size: FontSizes.normal;
        }

        current_name := LineEdit {
            text: Settings.settings_presets[Settings.settings_preset_idx];
            font-size: FontSizes.normal;
        }

        Button {
            text <=> Translations.settings_save_text;
            clicked => {
                Settings.settings_presets[Settings.settings_preset_idx] = current_name.text;
                edit_name = false;
            }
        }
    }
}

component HintText inherits Text {
    in-out property <string> hint_text;
    font-size: FontSizes.small;
    color: ColorPalette.hint_color;
    text: root.hint_text;
}

component HeaderText inherits Text {
    font-size: FontSizes.header;
    height: SettingsSize.item_height;
    horizontal-alignment: TextHorizontalAlignment.center;
    vertical-alignment: TextVerticalAlignment.center;
}

component ConfigCacheButtons inherits HorizontalLayout {
    spacing: 20px;
    Button {
        text <=> Translations.settings_open_config_folder_text;
        clicked => {
            Callabler.open_config_folder();
        }
    }

    Button {
        text <=> Translations.settings_open_cache_folder_text;
        clicked => {
            Callabler.open_cache_folder();
        }
    }
}

component Languages inherits HorizontalLayout {
    spacing: 5px;
    Text {
        text <=> Translations.settings_language_text;
        vertical-alignment: TextVerticalAlignment.center;
        font-size: FontSizes.normal;
    }

    combo_box := ComboBox {
        current_index <=> Settings.language_index;
        model <=> Settings.languages_list;
        current-value <=> Settings.language_value;

        selected(item) => {
            Callabler.changed_language();
        }
    }
}

export component SettingsList inherits VerticalLayout {
    callback show_clean_cache_popup();

    preferred-height: 300px;
    preferred-width: 400px;

    in-out property <bool> restart_required_global;
    in-out property <bool> restart_required;

    Text {
        text <=> Translations.settings_settings_text;
        height: SettingsSize.item_height;
        horizontal-alignment: TextHorizontalAlignment.center;
        font-size: FontSizes.title;
    }

    ScrollView {
        VerticalLayout {
            padding-right: 15px;
            padding-bottom: 10px;
            spacing: 5px;

            HeaderText {
                text <=> Translations.settings_global_settings_text;
            }

            Presets {
                height: SettingsSize.item_height;
            }
            Languages {
                height: SettingsSize.item_height;
            }

            CheckBoxComponent {
                name <=> Translations.settings_dark_theme_text;
                model <=> Settings.dark_theme;
                toggled => {
                    Callabler.theme_changed();
                }   
            }

            CheckBoxComponent {
                name <=> Translations.settings_show_only_icons_text;
                model <=> Settings.show_only_icons;
            }
    
            CheckBoxComponent {
                name <=> Translations.settings_load_windows_size_at_startup_text;
                model <=> Settings.load_windows_size_at_startup;
            }
            
            CheckBoxComponent {
                name <=> Translations.settings_load_tabs_sizes_at_startup_text;
                model <=> Settings.load_tabs_sizes_at_startup;
            }

            CheckBoxComponent {
                name <=> Translations.settings_limit_lines_of_messages_text;
                model <=> Settings.limit_messages_lines;
            }

            CheckBoxComponent {
                name <=> Translations.settings_use_manual_application_scale_text;
                model <=> Settings.use_manual_application_scale;
                toggled => { restart_required_global = true; }
            }

            HintText {
                hint_text <=> Translations.settings_application_scale_hint_text;
            }

            ApplicationScaleComponent {
                name <=> Translations.settings_application_scale_text;
                changed => { restart_required_global = true; }
            }

            if restart_required_global: Text {
                text <=> Translations.settings_restart_required_scale_text;
                horizontal-alignment: TextHorizontalAlignment.center;
                font-size: FontSizes.normal;
            }

            CheckBoxComponent {
                enabled <=> GuiState.audio_feature_enabled;
                name <=> Translations.settings_play_audio_on_scan_completion_text;
                model <=> Settings.play_audio_on_scan_completion;
            }

            if !GuiState.audio_feature_enabled: HintText {
                hint_text: Translations.settings_audio_feature_hint_text;
            }

            if GuiState.audio_feature_enabled: HintText {
                hint_text: Translations.settings_audio_env_variable_hint_text;
            }

            HeaderText {
                text <=> Translations.settings_general_settings_text;
            }

            TextComponent {
                name <=> Translations.settings_excluded_items_text;
                model <=> Settings.excluded_items;
            }

            TextComponent {
                name <=> Translations.settings_allowed_extensions_text;
                model <=> Settings.allowed_extensions;
            }

            TextComponent {
                name <=> Translations.settings_excluded_extensions_text;
                model <=> Settings.excluded_extensions;
            }

            MinMaxSizeComponent { }

            CheckBoxComponent {
                name <=> Translations.settings_recursive_search_text;
                model <=> Settings.recursive_search;
            }

            CheckBoxComponent {
                name <=> Translations.settings_use_cache_text;
                model <=> Settings.use_cache;
            }

            CheckBoxComponent {
                name <=> Translations.settings_save_as_json_text;
                model <=> Settings.save_as_json;
            }

            CheckBoxComponent {
                name <=> Translations.settings_move_to_trash_text;
                model <=> Settings.move_to_trash;
            }

            CheckBoxComponent {
                name <=> Translations.settings_ignore_other_filesystems_text;
                model <=> Settings.ignore_other_filesystems;
            }

            CheckBoxComponent {
                name <=> Translations.settings_delete_outdated_cache_entries_text;
                model <=> Settings.delete_outdated_cache_entries;
            }

            HintText {
                hint_text <=> Translations.settings_delete_outdated_cache_entries_hint_text;
            }

            CheckBoxComponent {
                name <=> Translations.settings_hide_hard_links_text;
                model <=> Settings.hide_hard_links;
            }

            HintText {
                hint_text <=> Translations.settings_hide_hard_links_hint_text;
            }

            ThreadSliderComponent {
                name <=> Translations.settings_thread_number_text;
                maximum_number <=> GuiState.maximum_threads;
                changed => {
                    restart_required = true;
                }
            }

            if restart_required: Text {
                text <=> Translations.settings_restart_required_text;
                horizontal-alignment: TextHorizontalAlignment.center;
                font-size: FontSizes.normal;
            }
            HeaderText {
                text <=> Translations.tool_duplicate_files_text;
            }

            CheckBoxComponent {
                name <=> Translations.settings_duplicate_image_preview_text;
                model <=> Settings.duplicate_image_preview;
            }


            TextComponent {
                name <=> Translations.settings_duplicate_minimal_hash_cache_size_text;
                model <=> Settings.duplicate_minimal_hash_cache_size;
            }

            CheckBoxComponent {
                name <=> Translations.settings_duplicate_use_prehash_text;
                model <=> Settings.duplicate_use_prehash;
            }

            TextComponent {
                name <=> Translations.settings_duplicate_minimal_prehash_cache_size_text;
                model <=> Settings.duplicate_minimal_prehash_cache_size;
            }


            HeaderText {
                text <=> Translations.settings_similar_images_tool_text;
            }

            CheckBoxComponent {
                name <=> Translations.settings_similar_images_show_image_preview_text;
                model <=> Settings.similar_images_show_image_preview;
            }



            HeaderText {
                text <=> Translations.settings_similar_videos_tool_text;
            }

            CheckBoxComponent {
                name <=> Translations.settings_similar_videos_preview_text;
                model <=> Settings.video_thumbnails_preview;
            }


            HeaderText {
                text <=> Translations.settings_video_thumbnails_header_text;
            }

            CheckBoxComponent {
                name <=> Translations.settings_video_thumbnails_generate_text;
                model <=> Settings.video_thumbnails_generate;
            }

            CheckBoxComponent {
                name <=> Translations.settings_video_thumbnails_clear_unused_thumbnails_text;
                model <=> Settings.video_thumbnails_unused_thumbnails;
            }

            HorizontalLayout {
                spacing: 5px;
                Text {
                    text <=> Translations.settings_video_thumbnails_position_text;
                    vertical-alignment: TextVerticalAlignment.center;
                    height: SettingsSize.item_height;
                    font-size: FontSizes.normal;
                }
                Slider {
                    height: SettingsSize.item_height;
                    minimum <=> Settings.video_thumbnails_percentage_min;
                    maximum <=> Settings.video_thumbnails_percentage_max;
                    value <=> Settings.video_thumbnails_percentage;
                }
                Text {
                    text: "(" + round(Settings.video_thumbnails_percentage) + "%)";
                    vertical-alignment: TextVerticalAlignment.center;
                    height: SettingsSize.item_height;
                    font-size: FontSizes.normal;
                    min-width: 60px;
                }
            }

            CheckBoxComponent {
                name <=> Translations.settings_video_thumbnails_generate_grid_text;
                model <=> Settings.video_thumbnails_generate_grid;
            }

            HorizontalLayout {
                spacing: 5px;
                Text {
                    text <=> Translations.settings_video_thumbnails_generate_grid_hint_text;
                    vertical-alignment: TextVerticalAlignment.center;
                    font-size: FontSizes.small;
                    color: ColorPalette.hint_color;
                    wrap: TextWrap.word-wrap;
                }
            }

            HorizontalLayout {
                spacing: 5px;
                Text {
                    text <=> Translations.settings_video_thumbnails_grid_tiles_per_side_text;
                    vertical-alignment: TextVerticalAlignment.center;
                    font-size: FontSizes.normal;
                }

                Slider {
                    minimum <=> Settings.video_thumbnails_grid_tiles_per_side_min;
                    maximum <=> Settings.video_thumbnails_grid_tiles_per_side_max;
                    value <=> Settings.video_thumbnails_grid_tiles_per_side;
                }

                Text {
                    text: round(Settings.video_thumbnails_grid_tiles_per_side);
                    vertical-alignment: TextVerticalAlignment.center;
                    font-size: FontSizes.normal;
                    min-width: 60px;
                }
            }

            HorizontalLayout {
                spacing: 5px;
                Text {
                    text <=> Translations.settings_video_thumbnails_grid_tiles_per_side_hint_text;
                    vertical-alignment: TextVerticalAlignment.center;
                    font-size: FontSizes.small;
                    color: ColorPalette.hint_color;
                    wrap: TextWrap.word-wrap;
                }
            }

            HeaderText {
                text <=> Translations.settings_cache_header_text;
            }

            Button {
                text <=> Translations.settings_clean_cache_button_text;
                clicked => {
                    root.show_clean_cache_popup();
                }
            }

            if Translations.settings_cache_number_size_text != "": HeaderText {
                text <=> Translations.settings_cache_number_size_text;
            }
            if Translations.settings_video_thumbnails_number_size_text != "": HeaderText {
                text <=> Translations.settings_video_thumbnails_number_size_text;
            }
            if Translations.settings_log_number_size_text != "": HeaderText {
                text <=> Translations.settings_log_number_size_text;
            }

            ConfigCacheButtons { }
        }
    }

    HorizontalLayout {
        spacing: 5px;
        Button {
            text <=> Translations.settings_save_text;
            clicked => {
                Callabler.save_current_preset();
            }
        }

        Button {
            text <=> Translations.settings_load_text;
            clicked => {
                Callabler.load_current_preset();
            }
        }

        Button {
            text <=> Translations.settings_reset_text;
            clicked => {
                Callabler.reset_current_preset();
            }
        }
    }
}
