export global Settings {
    in-out property <int> settings_preset_idx: 0;
    in-out property <[string]> settings_presets: ["Preset 1", "Preset 2"];

    in-out property <[StandardListViewItem]> included_directories: [{text: "ABCD"}, {text: "BCDA"}];
    in-out property <[StandardListViewItem]> excluded_directories: [{text: "ABCD"}, {text: "BCDA"}, {text: "CDFFF"}];

    // Settings
    in-out property <string> excluded_items: "Excluded items";
    in-out property <string> allowed_extensions: "Allowed extensions";
    in-out property <string> minimum_file_size: 0;
    in-out property <string> maximum_file_size: 0;
    in-out property <bool> use_cache: false;
    in-out property <bool> save_as_json: false;
    in-out property <bool> move_to_trash: false;
    in-out property <bool> ignore_other_filesystems: false;
    in-out property <float> thread_number: 0;
}
