export global Translations {
    in-out property <string> yes_button_text: "Yes";
    in-out property <string> no_button_text: "No";
    in-out property <string> ok_button_text: "Ok";
    in-out property <string> cancel_button_text: "Cancel";
    in-out property <string> are_you_want_to_continue_text: "Are you want to continue?";
    
    // Main window
    in-out property <string> main_window_title_text: "Krokiet - Data Cleaner";

    // Bottom buttons
    in-out property <string> scan_button_text: "Scan";
    in-out property <string> stop_button_text: "Stop";
    in-out property <string> select_button_text: "Select";
    in-out property <string> move_button_text: "Move";
    in-out property <string> delete_button_text: "Delete";
    in-out property <string> save_button_text: "Save";
    in-out property <string> sort_button_text: "Sort";
    in-out property <string> rename_button_text: "Rename";

    // About
    in-out property <string> motto_text: "This program is free to use and will always be.\nSee the The MIT/GPL License for details.";
    in-out property <string> unicorn_text: "You may not look at unicorn, but unicorn always looks at you.";
    in-out property <string> repository_text: "Repository";
    in-out property <string> instruction_text: "Instruction";
    in-out property <string> donation_text: "Donation";
    in-out property <string> translation_text: "Translation";

    // Bottom items
    in-out property <string> included_directories_text: "Included Directories";
    in-out property <string> excluded_directories_text: "Excluded Directories";
    in-out property <string> ref_text: "Ref";
    in-out property <string> path_text: "Path";

    // Tools
    in-out property <string> tool_duplicate_files_text: "Duplicate Files";
    in-out property <string> tool_empty_folders_text: "Empty Folders";
    in-out property <string> tool_big_files_text: "Big Files";
    in-out property <string> tool_empty_files_text: "Empty Files";
    in-out property <string> tool_temporary_files_text: "Temporary Files";
    in-out property <string> tool_similar_images_text: "Similar Images";
    in-out property <string> tool_similar_videos_text: "Similar Videos";
    in-out property <string> tool_music_duplicates_text: "Music Duplicates";
    in-out property <string> tool_invalid_symlinks_text: "Invalid Symlinks";
    in-out property <string> tool_broken_files_text: "Broken Files";
    in-out property <string> tool_bad_extensions_text: "Bad Extensions";

    // Sorting
    in-out property <string> sort_by_item_name_text: "Sort by item name";
    in-out property <string> sort_by_parent_name_text: "Sort by parent folder";
    in-out property <string> sort_by_full_name_text: "Sort by full name";
    in-out property <string> sort_by_size_text: "Sort by size";
    in-out property <string> sort_by_modification_date_text: "Sort by modification date";
    in-out property <string> sort_by_selection_text: "Sort by selection";
    in-out property <string> sort_reverse_text: "Reverse sort";
    in-out property <string> sort_by_checked_text: "Sort by check status";

    // Selection
    in-out property <string> selection_all_text: "Select all";
    in-out property <string> selection_deselect_all_text: "Unselect all";
    in-out property <string> selection_invert_selection_text: "Invert selection";
    in-out property <string> selection_the_biggest_size_text: "Select the biggest size";
    in-out property <string> selection_the_biggest_resolution_text: "Select the biggest resolution";
    in-out property <string> selection_the_smallest_size_text: "Select the smallest size";
    in-out property <string> selection_the_smallest_resolution_text: "Select the smallest resolution";
    in-out property <string> selection_newest_text: "Select newest";
    in-out property <string> selection_oldest_text: "Select oldest";

    // Progress
    in-out property <string> stage_current_text: "Current Stage:";
    in-out property <string> stage_all_text: "All Stages:";

    // Subsettings
    in-out property <string> subsettings_text: "Subsettings";
    in-out property <string> subsettings_images_hash_size_text: "Hash Size";
    in-out property <string> subsettings_images_resize_algorithm_text: "Resize Algorithm";
    in-out property <string> subsettings_images_ignore_same_size_text: "Ignore same size";
    in-out property <string> subsettings_images_max_difference_text: "Max difference";

    in-out property <string> subsettings_images_duplicates_hash_type_text: "Hash Type";

    in-out property <string> subsettings_duplicates_check_method_text: "Check method";
    in-out property <string> subsettings_duplicates_name_case_sensitive_text: "Case Sensitive(only name modes)";

    in-out property <string> subsettings_biggest_files_sub_method_text: "Method";
    in-out property <string> subsettings_biggest_files_sub_number_of_files_text: "Number of files";

    in-out property <string> subsettings_videos_max_difference_text: "Max difference";
    in-out property <string> subsettings_videos_ignore_same_size_text: "Ignore same size";

    in-out property <string> subsettings_music_audio_check_type_text: "Audio check type";
    in-out property <string> subsettings_music_approximate_comparison_text: "Approximate Tag Comparison";
    in-out property <string> subsettings_music_compared_tags_text: "Compared tags";
    in-out property <string> subsettings_music_title_text: "Title";
    in-out property <string> subsettings_music_artist_text: "Artist";
    in-out property <string> subsettings_music_bitrate_text: "Bitrate";
    in-out property <string> subsettings_music_genre_text: "Genre";
    in-out property <string> subsettings_music_year_text: "Year";
    in-out property <string> subsettings_music_length_text: "Length";
    in-out property <string> subsettings_music_max_difference_text: "Max difference";
    in-out property <string> subsettings_music_minimal_fragment_duration_text: "Minimal fragment duration";
    in-out property <string> subsettings_music_compare_fingerprints_only_with_similar_titles_text: "Compare only with similar titles";

    in-out property <string> subsettings_broken_files_type_text: "Type of files to check";
    in-out property <string> subsettings_broken_files_audio_text: "Audio";
    in-out property <string> subsettings_broken_files_pdf_text: "Pdf";
    in-out property <string> subsettings_broken_files_archive_text: "Archive";
    in-out property <string> subsettings_broken_files_image_text: "Image";

    // Settings
    in-out property <string> settings_dark_theme_text: "Dark theme";
    in-out property <string> settings_show_only_icons_text: "Show only icons";
    in-out property <string> settings_excluded_items_text: "Excluded item:";
    in-out property <string> settings_allowed_extensions_text: "Allowed extensions:";
    in-out property <string> settings_excluded_extensions_text: "Excluded extensions:";
    in-out property <string> settings_file_size_text: "File Size(Kilobytes)";
    in-out property <string> settings_minimum_file_size_text: "Min:";
    in-out property <string> settings_maximum_file_size_text: "Max:";
    in-out property <string> settings_recursive_search_text: "Recursive search";
    in-out property <string> settings_use_cache_text: "Use cache";
    in-out property <string> settings_save_as_json_text: "Also save cache as JSON file";
    in-out property <string> settings_move_to_trash_text: "Move deleted files to trash";
    in-out property <string> settings_ignore_other_filesystems_text: "Ignore other filesystems (only Linux)";
    in-out property <string> settings_thread_number_text: "Thread number";
    in-out property <string> settings_restart_required_text: "---You need to restart app to apply changes in thread number---";
    in-out property <string> settings_duplicate_image_preview_text: "Image preview";
    in-out property <string> settings_duplicate_hide_hard_links_text: "Hide hard links";
    in-out property <string> settings_duplicate_minimal_hash_cache_size_text: "Minimal size of cached files - Hash (KB)";
    in-out property <string> settings_duplicate_use_prehash_text: "Use prehash";
    in-out property <string> settings_duplicate_minimal_prehash_cache_size_text: "Minimal size of cached files - Prehash (KB)";
    in-out property <string> settings_duplicate_delete_outdated_entries_text: "Delete automatically outdated entries";
    in-out property <string> settings_similar_images_show_image_preview_text: "Image preview";
    in-out property <string> settings_similar_images_hide_hard_links_text: "Hide hard links";
    in-out property <string> settings_delete_outdated_entries_text: "Delete automatically outdated entries";
    in-out property <string> settings_similar_videos_hide_hard_links_text: "Hide hard links";
    in-out property <string> settings_open_config_folder_text: "Open config folder";
    in-out property <string> settings_open_cache_folder_text: "Open cache folder";
    in-out property <string> settings_language_text: "Language";
    in-out property <string> settings_current_preset_text: "Current Preset:";
    in-out property <string> settings_edit_name_text: "Edit name";
    in-out property <string> settings_choose_name_for_prefix_text: "Choose name for prefix ";
    in-out property <string> settings_save_text: "Save";
    in-out property <string> settings_load_text: "Load";
    in-out property <string> settings_reset_text: "Reset";
    in-out property <string> settings_similar_videos_tool_text: "Similar Videos tool";
    in-out property <string> settings_similar_images_tool_text: "Similar Images tool";
    in-out property <string> settings_similar_music_tool_text: "Similar Music tool";
    in-out property <string> settings_duplicate_tool_text: "Duplicate tool";
    in-out property <string> settings_general_settings_text: "General Settings";
    in-out property <string> settings_global_settings_text: "Global Settings";
    in-out property <string> settings_settings_text: "Settings";

    // Popup Save
    in-out property <string> popup_save_title_text: "Saving results";
    in-out property <string> popup_save_message_text: "This will save results to 3 different files";

    // Popup rename
    in-out property <string> popup_rename_title_text: "Renaming files";
    in-out property <string> popup_rename_message_text: "This will rename extensions of selected files to more proper";

    // Popup new directories
    in-out property <string> popup_new_directories_title_text: "Manually adding directories(one per line)";

    // Popup move folders
    in-out property <string> popup_move_title_text: "Moving files";
    in-out property <string> popup_move_message_text: "Moving entries to folder"; // TODO remove
    in-out property <string> popup_move_copy_checkbox_text: "Copy files instead of moving";
    in-out property <string> popup_move_preserve_folder_checkbox_text: "Preserve folder structure";

    // Popup delete
    in-out property <string> delete_text: "Delete items";
    in-out property <string> delete_confirmation_text: "Are you sure you want to delete the selected items?";

    // Main window
    in-out property <string> stopping_scan_text: "Stopping scan, please wait...";
    in-out property <string> searching_text: "Searching...";
}
