export global Translations {
    in-out property <string> yes_button_text: "Yes";
    in-out property <string> no_button_text: "No";
    
    // Bottom buttons
    in-out property <string> scan_button_text: "Scan";
    in-out property <string> stop_button_text: "Stop";
    in-out property <string> select_button_text: "Select";
    in-out property <string> move_button_text: "Move";
    in-out property <string> delete_button_text: "Delete";
    in-out property <string> save_button_text: "Save";
    in-out property <string> sort_button_text: "Sort";
    in-out property <string> rename_button_text: "Rename";

    // About
    in-out property <string> motto_text: "This program is free to use and will always be.\nSee the The MIT/GPL License for details.";
    in-out property <string> unicorn_text: "You may not look at unicorn, but unicorn always looks at you.";
    in-out property <string> repository_text: "Repository";
    in-out property <string> instruction_text: "Instruction";
    in-out property <string> donation_text: "Donation";
    in-out property <string> translation_text: "Translation";

    // Bottom items
    in-out property <string> add_button_text: "Add";
    in-out property <string> remove_button_text: "Remove";
    in-out property <string> manual_add_button_text: "Manual Add";
    in-out property <string> included_directories_text: "Included Directories";
    in-out property <string> excluded_directories_text: "Excluded Directories";
    in-out property <string> ref_text: "Ref";
    in-out property <string> path_text: "Path";

    // Popup delete
    in-out property <string> delete_text: "Delete items";
    in-out property <string> delete_confirmation_text: "Are you sure you want to delete the selected items?";

    // Tools
    in-out property <string> tool_duplicate_files_text: "Duplicate Files";
    in-out property <string> tool_empty_folders_text: "Empty Folders";
    in-out property <string> tool_big_files_text: "Big Files";
    in-out property <string> tool_empty_files_text: "Empty Files";
    in-out property <string> tool_temporary_files_text: "Temporary Files";
    in-out property <string> tool_similar_images_text: "Similar Images";
    in-out property <string> tool_similar_videos_text: "Similar Videos";
    in-out property <string> tool_music_duplicates_text: "Music Duplicates";
    in-out property <string> tool_invalid_symlinks_text: "Invalid Symlinks";
    in-out property <string> tool_broken_files_text: "Broken Files";
    in-out property <string> tool_bad_extensions_text: "Bad Extensions";







}
