name: czkawka # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '3.3.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Czkawka - fast data cleaner written in Rust # 79 char long summary
description: |
  Czkawka is very fast and feature rich cleaner which finds file duplicates, empty folders and files, duplicated music, similar images or the biggest files in selected directories.
  This program have frontend written in modern GTK 3.
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  czkawka:
    plugin: rust
    source: https://github.com/qarmin/czkawka.git
    build-packages:
      - libasound2-dev
      - curl
      - gcc
      - git
    rust-path: ["czkawka_gui"]
apps:
  czkawka:
    command: bin/czkawka_gui
    extensions: [gnome-3-38]
    plugs:
      - home
      - removable-media
      - udisks2
