name: 🐧 Linux CLI
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 2'

env:
  CARGO_TERM_COLOR: always

jobs:
  linux-cli:
    strategy:
      matrix:
        toolchain: [ stable, 1.67.1 ]
        type: [ release ]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Install basic libraries
        run: sudo apt-get update; sudo apt install libheif-dev -y

      - name: Setup rust version
        run: rustup default ${{ matrix.toolchain }}

      - name: Build Release
        run: cargo build --release --bin czkawka_cli
        env:
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: "-C debuginfo=0"
        if: ${{ (matrix.type == 'release') }}

      - name: Store Linux CLI
        uses: actions/upload-artifact@v3
        with:
          name: czkawka_cli-${{ runner.os }}-${{ matrix.toolchain }}
          path: target/release/czkawka_cli
        if: ${{ matrix.type == 'release' }}

      # Duplicate finder checks included and excluded directories
      # Others are just check delete files number
      - name: Linux Regression Test
        run: |
          wget https://github.com/qarmin/czkawka/releases/download/1.1.0/TestSuite.zip
          unzip TestSuite.zip -d TestSuite
          python3 misc/check_results.py TestSuite 15 8


          target/release/czkawka_cli dup -d "$(pwd)/TestSuite" -D aen -m 1024
          python3 misc/check_results.py TestSuite 7 8

          rm -rf TestSuite
          unzip TestSuite.zip -d TestSuite

          target/release/czkawka_cli dup -d "$(pwd)/TestSuite" -D aen -m 1024
          python3 misc/check_results.py TestSuite 7 8

          rm -rf TestSuite
          unzip TestSuite.zip -d TestSuite

          target/release/czkawka_cli dup -d "$(pwd)/TestSuite" -x TEXT -D aeo -m 1024
          python3 misc/check_results.py TestSuite 14 8

          rm -rf TestSuite
          unzip TestSuite.zip -d TestSuite

          target/release/czkawka_cli dup -d "$(pwd)/TestSuite" -e "$(pwd)/TestSuite/SubFolder" -D aeo -m 1024
          python3 misc/check_results.py TestSuite 13 8

          rm -rf TestSuite
          unzip TestSuite.zip -d TestSuite

          target/release/czkawka_cli dup -d "$(pwd)/TestSuite" -m 1500 -D aeo
          python3 misc/check_results.py TestSuite 8 8

          rm -rf TestSuite
          unzip TestSuite.zip -d TestSuite

          target/release/czkawka_cli dup -d "$(pwd)/TestSuite" -R -m 1024
          python3 misc/check_results.py TestSuite 15 8
          target/release/czkawka_cli dup -d "$(pwd)/TestSuite" -R -D aeo -m 1024
          python3 misc/check_results.py TestSuite 13 8


          target/release/czkawka_cli big -d "$(pwd)/TestSuite"

          rm -rf TestSuite
          unzip TestSuite.zip -d TestSuite

          target/release/czkawka_cli empty-files -d "$(pwd)/TestSuite"
          python3 misc/check_results.py TestSuite 15 8
          target/release/czkawka_cli empty-files -d "$(pwd)/TestSuite" -D
          python3 misc/check_results.py TestSuite 13 8

          rm -rf TestSuite
          unzip TestSuite.zip -d TestSuite

          target/release/czkawka_cli empty-folders -d "$(pwd)/TestSuite"
          python3 misc/check_results.py TestSuite 15 8
          target/release/czkawka_cli empty-folders -d "$(pwd)/TestSuite" -D
          python3 misc/check_results.py TestSuite 15 2

          rm -rf TestSuite
          unzip TestSuite.zip -d TestSuite

          target/release/czkawka_cli temp -d "$(pwd)/TestSuite"
          python3 misc/check_results.py TestSuite 15 8
          target/release/czkawka_cli temp -d "$(pwd)/TestSuite" -D
          python3 misc/check_results.py TestSuite 14 8
