name: 🐧 Linux CLI
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 2'

env:
  CARGO_TERM_COLOR: always

jobs:
  linux-cli:
    strategy:
      matrix:
        toolchain: [ stable, 1.75.0 ]
        type: [ release ]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Install basic libraries
        run: sudo apt update || true; sudo apt install libheif-dev ffmpeg -y

      - name: Setup rust version
        run: rustup default ${{ matrix.toolchain }}

      - name: Enable LTO
        run: sed -i 's/#lto = "thin"/lto = "thin"/g' Cargo.toml
        if: ${{ (matrix.type == 'release') }}

      - name: Build Release
        run: cargo build --release --bin czkawka_cli
        if: ${{ (matrix.type == 'release') }}

      - name: Store Linux CLI
        uses: actions/upload-artifact@v4
        with:
          name: czkawka_cli-${{ runner.os }}-${{ matrix.toolchain }}
          path: target/release/czkawka_cli
        if: ${{ matrix.type == 'release' }}

      - name: Linux Regression Test
        run: |
          wget https://github.com/qarmin/czkawka/releases/download/6.0.0/TestFiles.zip
          cd ci_tester
          cargo build --release
          cd ..
          
          ci_tester/target/release/ci_tester target/release/czkawka_cli
        if: ${{ matrix.type == 'release' }}
