name: 🐧 Linux CLI
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 2'

env:
  CARGO_TERM_COLOR: always

jobs:
  linux-cli:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Install basic libraries
        run: sudo apt update || true; sudo apt install libheif-dev libraw-dev ffmpeg -y

      - name: Setup rust version
        run: rustup default stable

      - name: Enable LTO
        run: sed -i 's/#lto = "thin"/lto = "thin"/g' Cargo.toml

      - name: Build Release
        run: cargo build --release --bin czkawka_cli

      - name: Store Linux CLI
        uses: actions/upload-artifact@v4
        with:
          name: czkawka_cli-${{ runner.os }}
          path: target/release/czkawka_cli

      - name: Build test version
        run: cargo build --profile test --bin czkawka_cli

      - name: Linux Regression Test
        run: |
          wget https://github.com/qarmin/czkawka/releases/download/6.0.0/TestFiles.zip
          cd ci_tester
          cargo build --release
          cd ..
          
          ci_tester/target/release/ci_tester target/debug/czkawka_cli

      - name: Prepare files to release
        run: |
          mv target/release/czkawka_cli linux_czkawka_cli
      - name: Release
        uses: softprops/action-gh-release@v2
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          tag_name: "Nightly"
          files: |
            linux_czkawka_cli
          token: ${{ secrets.PAT_REPOSITORY }}