name: 🐧 Linux CLI ARM
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 2'

env:
  CARGO_TERM_COLOR: always

jobs:
  linux-arm:
    runs-on: ubuntu-22.04-arm
    steps:
      - uses: actions/checkout@v4

      - name: Install basic libraries
        run: sudo apt update || true;

      - name: Setup rust version
        run: rustup default 1.85.0

      - name: Enable LTO
        if: ${{ github.ref == 'refs/heads/master' }}
        run: sed -i 's/#lto = "thin"/lto = "thin"/g' Cargo.toml

      - name: Build Release
        run: cargo build --release

      - name: Store cli
        uses: actions/upload-artifact@v4
        with:
          name: czkawka_cli-${{ runner.os }}
          path: |
            target/release/czkawka_cli

      - name: Store gui
        uses: actions/upload-artifact@v4
        with:
          name: czkawka_gui-${{ runner.os }}
          path: |
            target/release/czkawka_gui

      - name: Store krokiet
        uses: actions/upload-artifact@v4
        with:
          name: krokiet-${{ runner.os }}
          path: |
            target/release/krokiet
      - name: Prepare files to release
        run: |
          mv target/release/czkawka_cli linux_czkawka_cli_arm
          mv target/release/czkawka_gui linux_czkawka_gui_arm
          mv target/release/krokiet linux_krokiet_arm

      - name: Release
        uses: softprops/action-gh-release@v2
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          tag_name: "Nightly"
          files: |
            linux_czkawka_cli_arm
            linux_czkawka_gui_arm
            linux_krokiet_arm
          token: ${{ secrets.PAT_REPOSITORY }}